// AUTO-GENERATED legal document content (source: legal-inbound/*.docx, current approved drafts).
// Internal review notes stripped for public display. Do NOT expose review/risk-acceptance status here.
// The Informed Use & Safety Disclosure is NOT here — it renders from lib/companion/disclosures.ts
// (single source of truth shared with the in-app acceptance gate).

export interface LegalDoc {
  slug: string;
  title: string;
  effectiveDate: string;
  lastUpdated?: string;
  markdown: string;
}

export const LEGAL_DOCS: Record<string, LegalDoc> = {
  "privacy": {
    slug: "privacy",
    title: "Symmetricly Privacy Policy",
    effectiveDate: "July 25, 2026",
    lastUpdated: "July 25, 2026",
    markdown: `Symmetricly respects your privacy and recognizes that relationships, personal development, and emotional well-being can involve deeply personal information.

This Privacy Policy explains how Symmetricly (“Symmetricly,” “we,” “us,” or “our”) collects, uses, stores, shares, and protects information when you use our websites, accounts, educational products, assessments, digital tools, and other consumer relationship-wellness services.

Please read this Privacy Policy carefully before using our services.

## 1. Scope of This Privacy Policy

This Privacy Policy applies to Symmetricly's consumer-facing relationship education and wellness services, including, where applicable:

- Symmetricly websites;

- Relationship Life Cycle™ educational content;

- Relationship Life Cycle™ assessments and results;

- the Relationship Companion;

- educational programs and digital learning experiences;

- user accounts and portals;

- digital resources, workbooks, and related materials;

- purchases and subscriptions;

- communications with Symmetricly; and

- other consumer relationship-wellness features that link to this Privacy Policy.

Certain products or features may include additional privacy notices. Those notices supplement this Privacy Policy and should be read together with it.

### Clinical Services

This Privacy Policy is not intended to replace privacy notices applicable to psychotherapy, counseling, or other clinical healthcare services provided through a separate Symmetricly-affiliated clinical practice.

If you receive clinical services, information created or maintained as part of that professional relationship may be subject to separate clinical privacy practices, consent documents, and applicable healthcare privacy laws.

Using a Symmetricly educational or relationship-wellness product does not, by itself, establish a therapist-client relationship.

## 2. Information We Collect

The information we collect depends on which Symmetricly services you use and how you interact with them.

### A. Account Information

When you create or maintain an account, we may collect information such as:

- name;

- email address;

- account identifiers;

- authentication information;

- account status;

- preferences;

- enrollment or access information; and

- records associated with account creation, authentication, or administration.

Passwords and authentication credentials may be processed through our authentication service providers rather than being directly accessible to Symmetricly personnel in readable form.

### B. Information You Provide

When you use interactive Symmetricly services, you may choose to provide information about yourself, your experiences, relationships, goals, concerns, or circumstances.

Depending on the feature, this may include:

- responses to assessments or questionnaires;

- relationship status or context;

- reflections;

- journal-style responses;

- Relationship Companion entries;

- Blueprint or planning information;

- goals and milestones;

- preferences and interests;

- feedback;

- support requests; and

- other information you voluntarily enter.

Some of this information may be sensitive or highly personal.

You are not required to enter information you do not wish to record digitally.

## 3. Assessment Information

When you complete a Relationship Life Cycle™ assessment or similar educational tool, we may collect:

- your responses;

- assessment completion information;

- structural or relationship-context information;

- calculated or derived assessment results;

- educational interpretations;

- developmental or relational indicators generated by the assessment system; and

- related technical information necessary to provide your results.

Assessment results are intended for educational and relationship-wellness purposes unless a particular product expressly states otherwise.

They are not, by themselves, mental-health diagnoses, medical diagnoses, legal conclusions, professional safety assessments, or guarantees about the future of a relationship.

## 4. Relationship Companion Information

If you use the Relationship Companion, you may choose to enter free-text information about relationships, experiences, concerns, decisions, goals, or other personal matters.

The Companion may store information necessary to provide its features, such as:

- guided-experience responses;

- reflections;

- Blueprint information;

- Conversation Planner information;

- Journey information;

- progress or status information;

- interests;

- milestones; and

- other Companion content you choose to save.

Because free-text relationship reflections may contain sensitive information, you should consider what you are comfortable storing digitally before entering it.

Additional information about the Companion is provided in the Relationship Companion Privacy Disclosure and Informed Use & Safety Disclosure.

## 5. Safety Detection Information

The Relationship Companion may use automated safety-detection rules to identify certain language that may indicate concerns involving:

- suicide or self-harm;

- intimate partner violence, threats, intimidation, or coercive control;

- sexual assault or sexual coercion;

- potential serious harm to another person; or

- possible immediate danger.

Safety detection occurs as part of processing certain free-text Companion features.

Depending on what is detected, the Companion may display a notice, pause or modify the ordinary experience, prioritize safety information, or provide relevant support resources.

Detection does not automatically cause Symmetricly to call emergency services, contact a hotline, notify another person, send an email or text on your behalf, or initiate real-time human monitoring.

Automated safety detection has limitations. Receiving or not receiving a safety message should not be interpreted as a professional determination of whether you or another person is safe.

## 6. Safety Event Metadata

When the safety system detects qualifying language, Symmetricly may create a structured safety-event record for security, system operation, auditing, quality assurance, and safety-system maintenance.

Depending on the event, this record may include information such as:

- safety category or categories;

- response or action level;

- immediate-danger indicator;

- classification information;

- safety-system version;

- safety-rule or registry version;

- relevant technical context;

- timestamps; and

- references necessary to associate the event with the applicable Companion activity.

The safety-event record is designed not to create an additional copy of your complete free-text disclosure solely for safety logging.

The original content you chose to save may remain stored as part of your Companion content according to the normal operation and retention of that feature.

## 7. Transaction and Purchase Information

When you purchase a Symmetricly product or subscription, we may collect or receive information such as:

- product purchased;

- purchase date;

- transaction identifiers;

- payment status;

- subscription status;

- entitlement or access status;

- refund information;

- dispute or chargeback status; and

- information necessary to reconcile purchases and provide or revoke access.

Payment-card information is processed by our payment processor. Symmetricly does not need to store your full payment-card number in order to provide account entitlements.

Payment, refund, dispute, and entitlement records may be retained when necessary for financial, fraud-prevention, accounting, audit, dispute, or legal purposes.

## 8. Technical and Usage Information

When you use our services, we or our service providers may automatically receive certain technical information, which may include:

- device or browser information;

- IP address;

- timestamps;

- pages or features accessed;

- authentication and session information;

- application errors;

- security events;

- general usage events; and

- information necessary to maintain, secure, troubleshoot, and improve the platform.

We seek to avoid placing sensitive free-text Companion disclosures into analytics, URLs, browser console output, or unnecessary application logs.

## 9. How We Use Information

We may use information collected through Symmetricly services to:

- create and maintain accounts;

- authenticate users;

- provide requested products and services;

- administer assessments;

- generate and display educational results;

- provide Relationship Companion functionality;

- save user progress and content;

- process purchases and subscriptions;

- determine and manage access entitlements;

- process refunds, disputes, suspensions, revocations, and restorations;

- deliver transactional communications;

- provide customer support;

- maintain safety features;

- secure our systems and prevent misuse;

- troubleshoot technical problems;

- maintain audit and operational records;

- understand general service usage;

- improve our services;

- comply with applicable obligations; and

- enforce our Terms of Use and other policies.

We do not use the Relationship Companion as a real-time emergency-monitoring service.

## 10. Automated Processing

Certain Symmetricly services use automated logic to provide functionality.

For example:

- assessments may calculate results based on submitted responses;

- the Relationship Companion may select or present educational experiences based on user activity or information;

- safety rules may classify certain language and determine which safety response should be displayed;

- account and payment systems may determine whether a user has valid access to a purchased product.

Automated systems can make mistakes and may not fully understand context, humor, slang, indirect language, or complex human circumstances.

Unless expressly stated otherwise, automated educational outputs should not be treated as professional diagnoses, individualized clinical determinations, legal conclusions, or professional safety assessments.

## 11. How We Share Information

We do not sell your personal information to advertisers.

We may disclose information when reasonably necessary to operate Symmetricly, including to service providers that perform functions on our behalf.

Depending on the service, those functions may include:

- website hosting;

- database and storage infrastructure;

- authentication;

- payment processing;

- transactional email and communications delivery;

- security and fraud prevention;

- technical infrastructure and operations; and

- other services necessary to operate the platform.

Service providers receive information according to the services they perform and their applicable agreements and privacy practices.

We may also disclose information when required by law, legal process, or valid governmental request, or when reasonably necessary to protect our rights, investigate fraud or misuse, enforce our agreements, or address legal obligations.

## 12. Current Service-Provider Categories

Our technology infrastructure may include third-party providers for functions such as:

- hosting and application delivery;

- database infrastructure and authentication;

- payment processing;

- transactional email delivery;

- customer-relationship and marketing-automation services;

- automated text-generation (artificial-intelligence) services used to produce certain educational narrative content;

- website analytics and advertising measurement;

- security and operational infrastructure.

At the time of this Policy, providers used for these functions may include Netlify (hosting and application delivery), Supabase (database infrastructure and authentication), Stripe (payment processing), Resend (transactional email delivery), GoHighLevel (customer-relationship and marketing-automation services), Anthropic (automated text-generation used to produce certain educational narrative content), and — where enabled — Google Analytics and the Meta Pixel (website analytics and advertising measurement).

Our service-provider relationships may change as the platform develops.

Not every provider receives every category of personal information. For example, the customer-relationship provider may receive contact information and assessment-outcome information associated with a lead; the automated text-generation provider may process assessment-derived information used to generate an educational narrative; and analytics or advertising providers may receive usage and event information associated with your visit.

We seek to limit information provided to service providers to what is reasonably necessary for their function.

## 13. Third-Party Safety and Support Resources

Symmetricly may display contact information or links for independent crisis, domestic-violence, sexual-assault, emergency, or other support organizations.

You decide whether to contact or open these resources.

Unless expressly stated otherwise, these organizations are independent of Symmetricly. Their privacy policies, data practices, availability, and services are governed by their own practices.

Symmetricly does not control information you voluntarily provide directly to an independent resource after leaving or contacting it.

## 14. Human Access to Information

Relationship Companion responses are not continuously monitored by Symmetricly personnel.

Authorized personnel or service providers may have limited access to information when reasonably necessary to:

- operate or maintain the platform;

- investigate technical or security problems;

- provide requested support;

- administer accounts;

- investigate misuse;

- comply with applicable obligations; or

- perform other authorized operational functions.

Such access is subject to applicable access controls, authorization requirements, and company policies.

The ability of authorized personnel to technically access information does not mean that Symmetricly routinely reads users' private relationship reflections.

## 15. Security

We use administrative, technical, and organizational safeguards designed to protect information appropriate to the nature of the services we provide.

These safeguards may include access controls, authentication protections, database authorization policies, encryption provided through our infrastructure, server-side privileged operations, environment separation, and security monitoring.

No website, database, network, transmission method, or storage system can be guaranteed to be completely secure.

You are responsible for maintaining the confidentiality of your account credentials and for considering the privacy of the device and network you use to access Symmetricly.

## 16. Device and Relationship Safety

If another person monitors or has access to your device, accounts, browser, email, network activity, or internet history, they may be able to discover your use of Symmetricly.

Certain Relationship Companion safety experiences may include a Quick Exit feature.

Quick Exit is intended to help you leave a sensitive screen quickly. It does not guarantee that browsing history, network activity, device records, account activity, or other evidence of your visit has been erased.

If digital privacy is a safety concern, consider whether the device you are using is appropriate for entering sensitive information.

## 17. Data Retention

We retain information for as long as reasonably necessary for the purposes for which it was collected and for legitimate operational, security, financial, audit, fraud-prevention, dispute-resolution, or legal purposes.

Different categories of information may have different retention periods.

Deleting particular Companion content or requesting deletion of Companion data may not necessarily delete:

- your underlying authentication account;

- financial transaction records;

- entitlement records;

- content-free usage or operational events;

- structured safety-event metadata;

- security or audit records;

- records necessary to address disputes or fraud; or

- information we are permitted or required to retain.

We should not retain information longer than reasonably necessary for the applicable purpose.

## 18. Account and Data Deletion

Where available, you may use account or product controls to delete certain information or request deletion.

The specific information removed depends on the request and the service involved.

For example, deletion of Relationship Companion data may remove saved Companion reflections, responses, plans, Blueprint information, milestones, interests, and related user content while certain financial, security, safety-event, operational, or entitlement records may be retained as described above.

Deletion of Companion content is not necessarily the same as deletion of your entire Symmetricly account.

Instructions for submitting privacy or deletion requests will be made available through the website or designated privacy contact.

## 19. Cookies and Similar Technologies

Symmetricly and its service providers may use cookies, local storage, session technologies, or similar mechanisms when necessary to:

- maintain authentication;

- preserve sessions;

- remember preferences;

- provide security protections;

- maintain application functionality; and

- understand appropriate service usage.

Where enabled on our public marketing website, we and our analytics and advertising providers (such as Google Analytics and the Meta Pixel) may also use cookies or similar technologies to measure website usage, evaluate the performance of our educational and marketing content, and understand how visitors reach our services. These analytics and advertising technologies are not essential to operate the service. They are not used within the authenticated Relationship Companion.

Where required by applicable law, we will provide additional information and an appropriate consent or opt-out mechanism before using non-essential analytics or advertising cookies or similar technologies. You may also control cookies through your browser settings, although disabling essential cookies may affect core functionality.

## 20. Communications

We may use your contact information to send communications related to your account or services, including:

- account verification;

- password or authentication messages;

- purchase confirmations;

- subscription or access notices;

- security communications;

- service changes;

- requested support; and

- other transactional messages.

Marketing communications, where offered, should provide an appropriate method to unsubscribe.

Unsubscribing from marketing messages may not prevent necessary transactional or account-related communications.

## 21. Children's Privacy

Symmetricly's consumer relationship-wellness services are not intended for children under 13.

We do not knowingly seek to collect personal information through these services from children under 13.

Certain educational programs intended for adolescents, schools, families, or other youth populations may be governed by separate enrollment procedures, privacy disclosures, parental or institutional permissions, and product-specific terms.

Do not use an adult consumer account to submit personal information about a child in a manner inconsistent with the applicable service.

## 22. State and Other Privacy Rights

Depending on where you live and applicable law, you may have rights concerning your personal information, which may include rights to request:

- access;

- correction;

- deletion;

- information about certain processing or disclosures; or

- other rights provided by applicable law.

These rights are not absolute and may be subject to exceptions, identity verification, retention requirements, and other legal limitations.

We will respond to valid privacy requests as required by applicable law.

## 23. Analytics, Advertising, and Sale or Sharing

Symmetricly does not sell your Relationship Companion disclosures or your assessment responses, and does not share those sensitive contents with advertisers for targeted advertising. These analytics and advertising technologies are not used within the authenticated Relationship Companion, and Symmetricly does not transmit Relationship Companion content, assessment responses, or safety-detection information to advertising or general-purpose analytics providers.

Where website analytics or advertising technologies (such as Google Analytics or the Meta Pixel) are enabled on our public marketing website, limited usage and event information associated with your visit — such as page views, conversion events, and associated online identifiers — may be processed by those providers. Depending on your jurisdiction, the use of such advertising technologies may be considered a “sale” or “sharing” of certain information for cross-context behavioral advertising under applicable privacy law.

Where applicable law provides a right to opt out of such sale or sharing, Symmetricly will honor valid opt-out requests and, where required, provide an opt-out mechanism or recognize an applicable opt-out preference signal. If Symmetricly’s advertising or analytics practices change in a way that creates additional disclosure or opt-out obligations, this Privacy Policy and the applicable privacy controls should be updated accordingly before those practices are implemented.

## 24. Changes to This Privacy Policy

We may update this Privacy Policy as our services, technology, or legal obligations change.

When we make changes, we will update the “Last Updated” date.

If a change materially affects how we handle information, we may provide additional notice when appropriate.

Continued use of our services after an updated Policy becomes effective may be subject to the updated Policy, except where additional consent is required.

## 25. Contact Us

If you have questions about this Privacy Policy or want to submit a privacy request, contact:

**Symmetricly**  
Email: info@symmetricly.co  
Mailing address: 1246 Concord Rd, Smyrna, GA 30080

Please do not send emergency or crisis requests to this contact information. This inbox is not monitored as an emergency-response service.

## 26. Relationship Companion Supplemental Disclosures

If you use the Relationship Companion, this Privacy Policy should be read together with the:

- Relationship Companion Privacy Disclosure;

- Relationship Companion Informed Use & Safety Disclosure; and

- Crisis & Safety Disclaimer.

If a Companion-specific disclosure provides additional information about how a particular Companion feature operates, that supplemental disclosure applies to that feature.`,
  },
  "terms": {
    slug: "terms",
    title: "Symmetricly Terms of Use",
    effectiveDate: "July 25, 2026",
    lastUpdated: "July 25, 2026",
    markdown: `These Terms of Use (“Terms”) govern your access to and use of Symmetricly's consumer-facing websites, digital platforms, educational programs, assessments, relationship-wellness tools, content, products, subscriptions, and related services.

These Terms form an agreement between you and 4 The Love Counseling & Consulting DBA Symmetricly, doing business as Symmetricly (“Symmetricly,” “we,” “us,” or “our”).

Please read these Terms carefully before using our services.

By creating an account, purchasing or accessing a product, selecting an acceptance button when presented, or otherwise using services governed by these Terms, you agree to these Terms and any additional terms or disclosures applicable to the specific product you use.

If you do not agree, do not use the applicable services.

## 1. Scope of These Terms

These Terms apply to Symmetricly's consumer relationship-education and wellness ecosystem, including, where applicable:

- Symmetricly websites;

- Relationship Life Cycle™ educational content;

- Relationship Life Cycle™ assessments;

- Relationship Snapshot™ and other assessment products;

- the Relationship Companion;

- The Relationship Academy and digital educational programs offered directly through Symmetricly;

- digital courses;

- educational resources;

- workbooks, journals, exercises, and guided experiences;

- user accounts and portals;

- subscriptions and paid digital products; and

- other consumer services that link to these Terms.

Certain services may have additional terms, disclosures, enrollment agreements, informed-use notices, refund policies, or privacy notices.

Those additional documents supplement these Terms.

If product-specific terms conflict with these general Terms concerning a matter unique to that product, the product-specific terms control for that matter unless otherwise stated.

## 2. Clinical Services Are Separate

Symmetricly may be affiliated with professionals or entities that provide psychotherapy, counseling, or other clinical services.

Consumer educational and relationship-wellness services governed by these Terms are separate from clinical treatment unless expressly stated otherwise.

Using a Symmetricly website, assessment, educational program, Relationship Companion feature, course, or other consumer product does not establish a therapist-client relationship.

Clinical services, when provided, are governed by separate informed-consent documents, professional agreements, privacy practices, and applicable laws.

Nothing in these Terms replaces the agreements governing an established clinical relationship.

## 3. Educational Purpose

Symmetricly provides relationship education, reflection tools, structured learning experiences, assessments, and relationship-wellness resources.

Unless expressly stated otherwise, these services are provided for educational and informational purposes.

They are not substitutes for:

- psychotherapy or counseling;

- medical or psychiatric treatment;

- diagnosis;

- legal advice;

- financial advice;

- crisis intervention;

- emergency services; or

- individualized professional assessment.

Content created or reviewed by licensed professionals does not convert a consumer educational service into psychotherapy or establish a professional treatment relationship.

## 4. No Guarantee of Relationship Outcomes

Relationships involve individual circumstances, choices, behaviors, histories, environments, and factors no digital product can fully evaluate.

Symmetricly does not guarantee that use of its services will:

- improve or preserve a relationship;

- prevent a breakup, separation, or divorce;

- result in reconciliation;

- produce a particular dating or relationship outcome;

- determine whether another person is compatible with you;

- determine whether you should remain in or leave a relationship;

- prevent conflict, abuse, harm, or loss; or

- produce any particular personal or emotional result.

You remain responsible for decisions you make based on your circumstances.

## 5. Relationship Life Cycle™ Framework

Certain Symmetricly products are based on the proprietary Relationship Life Cycle™ Framework.

The Framework may be used to organize relationship education, developmental concepts, assessments, guided experiences, curricula, and other materials.

Relationship Life Cycle™ outputs and terminology are intended to support education and reflection.

Unless expressly provided in a professional context governed by a separate agreement, they should not be interpreted as clinical diagnoses, medical determinations, legal conclusions, or guarantees concerning a relationship.

## 6. Assessments and Educational Results

Symmetricly may provide assessments, questionnaires, profiles, snapshots, or similar tools.

Assessment results may be generated from information you provide and applicable scoring or interpretation rules.

Results may include educational information about relationship context, relational functioning, developmental patterns, strengths, growth opportunities, or other concepts applicable to the particular assessment.

Assessment results:

- depend on the information provided;

- may be incomplete;

- may change as circumstances change;

- cannot capture every aspect of a relationship;

- should not be treated as diagnoses;

- do not establish whether a relationship is safe; and

- should not be the sole basis for major medical, legal, financial, or safety decisions.

Different Symmetricly tools may perform different functions. Use of an assessment does not mean that every Symmetricly product independently performs assessment or scoring.

## 7. Relationship Companion

The Relationship Companion is an educational relationship-wellness tool that may provide guided prompts, reflections, educational experiences, planning tools, and other applications of Relationship Life Cycle™ concepts.

The Companion is not psychotherapy, crisis care, or emergency monitoring.

No person is continuously monitoring Companion entries in real time.

The Companion may include automated safety features that respond to certain language concerning self-harm, violence, coercion, sexual safety, harm to others, or possible immediate danger.

Automated safety systems have limitations and may fail to identify concerning information or may flag information that is not an actual safety concern.

Receiving or not receiving a safety message does not constitute a professional safety assessment.

Before using the Relationship Companion, you may be required to acknowledge additional documents, including the:

- Relationship Companion Informed Use & Safety Disclosure;

- Relationship Companion Privacy Disclosure; and

- Crisis & Safety Disclaimer.

Those documents form part of the conditions applicable to your use of the Companion.

## 8. Emergency and Crisis Situations

Symmetricly's consumer digital services are not emergency-response systems.

Do not rely on Symmetricly websites, assessments, the Relationship Companion, email, support forms, or other digital services to request emergency assistance.

Symmetricly does not guarantee that anyone will see information you submit in time to respond to an emergency.

If you believe you or another person may be in immediate danger, seek appropriate emergency or crisis assistance when you can do so safely.

Any third-party crisis or support resources displayed through our services are provided for informational and access purposes and are operated independently unless expressly stated otherwise.

## 9. Eligibility

You must be legally capable of entering into these Terms to use services requiring an account or purchase.

Unless a particular service expressly permits otherwise, consumer accounts are intended for adults age 18 or older.

Products specifically developed for adolescents, schools, universities, parents, or other populations may have separate eligibility, consent, enrollment, or institutional requirements.

You agree not to create an account using false identifying information or impersonate another person.

## 10. Account Registration and Security

Certain Symmetricly services require an account.

You are responsible for:

- providing accurate account information;

- maintaining access to your registered email address where required;

- protecting your login credentials;

- preventing unauthorized use of your account; and

- notifying Symmetricly if you reasonably believe your account has been compromised.

You may not sell, transfer, share, or provide another person with access to an account or paid entitlement unless a particular product expressly permits shared access.

We may use authentication or security controls to protect accounts and services.

## 11. Privacy

Your use of Symmetricly services is also governed by the Symmetricly Privacy Policy.

Certain products may have supplemental privacy disclosures.

The Relationship Companion, for example, includes additional disclosures regarding free-text relationship information, automated safety detection, safety-event metadata, and related privacy considerations.

Please review applicable privacy notices before submitting sensitive information.

## 12. Purchases

Certain Symmetricly products require payment.

Prices, billing frequency, included features, and other purchase terms will be presented at or before checkout.

By completing a purchase, you authorize the applicable payment processor to charge the payment method you provide for the amount disclosed at checkout, including applicable recurring charges when purchasing a subscription.

Payment processing may be performed by a third-party payment processor.

You agree to provide accurate payment and billing information.

Access to a paid product may depend on successful confirmation of the applicable payment or subscription status.

## 13. Subscriptions

If you purchase a recurring subscription, you authorize recurring charges according to the billing frequency disclosed at checkout until the subscription is canceled or otherwise ends according to the applicable subscription terms.

Cancellation generally stops future renewal charges but does not necessarily create a refund for amounts already paid.

The exact timing of access after cancellation depends on the product and terms presented with the subscription.

If a particular subscription includes different cancellation or access rules, those product-specific rules control.

## 14. Refunds

Refund eligibility is governed by the refund policy applicable to the product purchased and any terms disclosed at checkout.

Unless otherwise required by law or expressly provided by an applicable refund policy:

- receiving a full refund may result in termination of access associated with the refunded purchase;

- a partial refund does not automatically terminate access;

- duplicate or erroneous payments may be handled according to the circumstances of the transaction; and

- issuing a refund does not require Symmetricly to delete account, financial, security, or transaction records that we are permitted or required to retain.

A refund associated with one purchase will not necessarily terminate access if another independent and valid entitlement continues to authorize access to the same product.

## 15. Payment Disputes and Chargebacks

If a payment is formally disputed or charged back through a payment provider or financial institution, Symmetricly may temporarily suspend access associated with the disputed payment while the dispute is pending.

If the dispute is resolved in Symmetricly's favor and the underlying payment remains valid, access associated with that payment may be restored.

If the dispute is resolved against Symmetricly and the payment is reversed, access associated with that payment may be revoked.

Suspension or revocation of one payment-based entitlement will not necessarily remove access if another independent, valid entitlement authorizes continued access.

Nothing in this section limits rights you may have under applicable law.

## 16. Promotional, Complimentary, and Administrative Access

Symmetricly may occasionally provide promotional, complimentary, scholarship, administrative, beta, testing, or other non-purchased access.

Such access may have separate eligibility, duration, or use conditions.

Unless otherwise promised in writing, complimentary or administrative access does not create a permanent right to continued access.

Symmetricly may correct entitlement errors or revoke access granted by mistake, subject to applicable law and any express commitments made to the user.

## 17. Digital Content and Availability

Digital products may be delivered through an account, online portal, download, streaming environment, community platform, or other digital mechanism.

We may update, improve, replace, reorganize, or discontinue particular features as the service evolves.

We do not guarantee uninterrupted or error-free availability.

Temporary interruptions may occur because of:

- maintenance;

- security updates;

- service-provider outages;

- internet disruptions;

- software errors;

- infrastructure changes; or

- circumstances outside our reasonable control.

Where a material change affects a paid product, we will handle the change consistent with applicable commitments and law.

## 18. Acceptable Use

You agree not to misuse Symmetricly services.

You may not:

- access another person's account without authorization;

- attempt to bypass authentication, payment, entitlement, or security controls;

- probe, scan, exploit, or attack the platform;

- interfere with service operation;

- introduce malicious code;

- scrape or systematically extract protected content without permission;

- use automated systems to reproduce substantial portions of proprietary materials;

- reverse engineer protected systems except where legally permitted;

- upload content that violates applicable law or the rights of another person;

- impersonate Symmetricly personnel;

- use the services to harass, threaten, stalk, exploit, or harm another person;

- use the services to facilitate unlawful conduct; or

- attempt to circumvent restrictions imposed on your account.

We may investigate suspected misuse and restrict or terminate access when reasonably necessary.

## 19. User-Submitted Content

Some Symmetricly services allow you to enter, save, or submit content.

You retain ownership of original content you provide, subject to the rights necessary for Symmetricly and its service providers to operate the service.

By submitting content, you authorize Symmetricly to host, store, process, reproduce, and technically use that content as reasonably necessary to:

- provide the feature you requested;

- maintain your account;

- process applicable automated functions;

- secure and troubleshoot the service;

- comply with applicable obligations; and

- perform other functions described in our Privacy Policy.

This permission does not transfer ownership of your original content to Symmetricly.

You are responsible for considering whether you have the right to submit information concerning another person and whether it is appropriate to record that information digitally.

## 20. Intellectual Property

Except for user-submitted content and third-party materials, Symmetricly's services and materials are owned by or licensed to Symmetricly and are protected by applicable intellectual-property laws.

This includes, as applicable:

- the Relationship Life Cycle™ Framework;

- framework architecture and terminology;

- assessments;

- scoring systems;

- educational interpretations;

- curricula;

- competency structures;

- guided experiences;

- exercises;

- workbooks;

- course materials;

- written content;

- graphics;

- branding;

- software interfaces;

- proprietary databases and content structures; and

- other original materials.

Your purchase or account gives you a limited right to use applicable materials for their intended personal or expressly authorized purpose.

It does not transfer ownership of Symmetricly intellectual property.

## 21. Prohibited Reproduction and Commercial Use

Unless Symmetricly provides written permission, you may not:

- reproduce substantial portions of paid materials;

- republish materials;

- sell or sublicense them;

- create competing assessments or curricula derived from proprietary materials;

- distribute account-only resources publicly;

- upload paid materials to public repositories or AI training datasets;

- use proprietary materials to train, fine-tune, benchmark, or build another commercial artificial-intelligence or machine-learning system;

- remove copyright, trademark, or proprietary notices; or

- commercially exploit Symmetricly intellectual property outside the license provided with your purchase.

Educators, clinicians, organizations, facilitators, and other professionals may require a separate professional license, certification, facilitator agreement, or institutional agreement to use certain Relationship Life Cycle™ materials with clients, students, employees, groups, or organizations.

## 22. Trademarks

Symmetricly, Relationship Life Cycle™, Relationship Snapshot™, Relationship Companion, and other names, logos, marks, program names, and branding used by Symmetricly may constitute trademarks or proprietary brand identifiers.

Nothing in these Terms grants permission to use Symmetricly's trademarks or branding in a way that suggests endorsement, certification, partnership, or affiliation without authorization.

## 23. Third-Party Services

Our services may contain integrations, links, resources, or functionality provided by third parties.

Third-party services operate under their own terms, privacy policies, and practices.

Symmetricly is not responsible for the independent operation, availability, content, privacy practices, or actions of third-party services except to the extent required by applicable law.

A link to a third-party service does not necessarily constitute endorsement.

## 24. Community Features

If Symmetricly offers community, discussion, group-learning, or similar interactive features, additional community guidelines may apply.

Information shared with other community participants should not be considered private merely because access to the community is restricted.

You are responsible for what you choose to share with other participants.

Harassment, threats, discriminatory abuse, exploitation, unauthorized solicitation, or other conduct inconsistent with applicable community rules may result in content removal or loss of community access.

## 25. Suspension and Termination

Symmetricly may suspend or terminate access when reasonably necessary because of:

- violation of these Terms;

- fraud or suspected fraud;

- unauthorized account use;

- security threats;

- payment reversal or loss of an applicable entitlement;

- misuse of the platform;

- legal requirements; or

- conduct that materially threatens users, Symmetricly, or the integrity of the service.

Where appropriate, suspension may be temporary while an issue is investigated or resolved.

Termination of access does not necessarily require deletion of records that may appropriately be retained under our Privacy Policy.

## 26. Disclaimers

To the fullest extent permitted by applicable law, Symmetricly services are provided on an “as is” and “as available” basis.

We do not warrant that:

- services will always be uninterrupted or error-free;

- automated systems will always interpret information correctly;

- educational content will apply perfectly to every situation;

- assessment results will predict future outcomes;

- safety-detection systems will identify every safety concern;

- third-party resources will always be available; or

- use of the services will produce a particular relationship, emotional, educational, financial, or personal outcome.

Nothing in these Terms excludes warranties or rights that cannot lawfully be excluded.

## 27. Limitation of Liability

To the fullest extent permitted by applicable law, Symmetricly and its owners, officers, employees, contractors, affiliates, and licensors will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from or relating to use of the services.

To the fullest extent permitted by applicable law, Symmetricly's aggregate liability arising from a particular paid consumer service will not exceed the amount you paid to Symmetricly for that service during the 12 months preceding the event giving rise to the claim.

These limitations do not apply where prohibited by law and do not limit liability that cannot legally be limited or excluded.

## 28. Indemnification

To the extent permitted by applicable law, you agree to indemnify and hold harmless Symmetricly and its officers, owners, employees, contractors, and affiliates from third-party claims, liabilities, damages, losses, and reasonable costs arising from:

- your unlawful misuse of the services;

- your violation of these Terms;

- content you submit in violation of another person's rights; or

- your infringement or misappropriation of another person's rights.

This provision does not require you to indemnify Symmetricly for conduct for which indemnification cannot lawfully be required.

## 29. Governing Law

These Terms are governed by the laws of the State of Georgia, without regard to conflict-of-law principles, except where applicable law requires otherwise.

Any mandatory rights available to you under applicable consumer law remain unaffected.

## 30. Dispute Resolution

Before filing a formal claim concerning these Terms or Symmetricly's consumer services, you and Symmetricly agree to make a reasonable good-faith effort to resolve the dispute informally.

A party initiating a dispute should provide written notice describing the issue and requested resolution.

Unless additional dispute-resolution terms are adopted, claims may be brought in a court with appropriate jurisdiction subject to applicable law.

## 31. Changes to Services and Terms

We may update these Terms as our services, technology, business practices, or legal obligations change.

The “Last Updated” date will identify the most recent revision.

For material changes, we may provide additional notice or require renewed acceptance where appropriate.

Changes will not retroactively eliminate rights that cannot lawfully be modified.

## 32. Electronic Communications and Acceptance

You consent to receive agreements, notices, disclosures, and other transactional communications electronically where permitted by law.

Electronic acceptance, including selecting an acceptance checkbox or button, may be used to record agreement to these Terms or applicable supplemental disclosures.

We may maintain records of:

- the document or version accepted;

- date and time of acceptance;

- applicable user or account identifier; and

- other technical information reasonably necessary to document acceptance.

## 33. Severability

If a provision of these Terms is determined to be unenforceable, the remaining provisions will continue in effect to the extent permitted by law.

An unenforceable provision should be interpreted or limited as necessary to best preserve its lawful purpose where permitted.

## 34. No Waiver

Failure by Symmetricly to enforce a provision of these Terms does not waive our right to enforce that provision later.

## 35. Entire Agreement

These Terms, together with the Privacy Policy and any applicable product-specific terms, enrollment agreements, disclosures, refund policies, or other incorporated documents, constitute the agreement governing your use of the applicable consumer service.

They do not replace separate agreements governing clinical treatment or other services expressly governed by different contracts.

## 36. Contact

Questions regarding these Terms may be directed to:

**Symmetricly**  
Email: info@symmetricly.co  
Mailing address: 1246 Concord Rd, Smyrna, GA 30080

Do not use this contact information to request emergency or crisis assistance. It is not monitored as an emergency-response service.

### Relationship Companion Documents

Relationship Companion users should also review:

- Symmetricly Privacy Policy;

- Relationship Companion Privacy Disclosure;

- Relationship Companion Informed Use & Safety Disclosure; and

- Crisis & Safety Disclaimer.`,
  },
  "refund": {
    slug: "refund",
    title: "Symmetricly Refund & Cancellation Policy",
    effectiveDate: "July 25, 2026",
    markdown: `This Refund & Cancellation Policy explains the general rules governing refunds, cancellations, duplicate payments, subscriptions, and access to paid consumer products and services offered by Symmetricly.

This Policy should be read together with the Symmetricly Terms of Use and any product-specific terms presented at the time of purchase.

## 1. General Policy

We want you to understand the terms of your purchase before you complete it.

Because Symmetricly offers different types of digital products, educational programs, subscriptions, assessments, and relationship-wellness services, refund eligibility may vary by product.

The refund or cancellation terms applicable to a purchase will be disclosed at or before checkout when they differ from this general Policy.

If product-specific refund terms are presented at checkout, those terms control for that purchase.

Nothing in this Policy limits refund, cancellation, or consumer rights that cannot legally be waived.

## 2. Digital Products and Immediately Accessible Content

Certain Symmetricly products provide immediate access to digital content or functionality after purchase.

These may include:

- assessments and assessment results;

- digital workbooks or resources;

- downloadable materials;

- courses or educational content;

- Relationship Companion access;

- digital tools;

- guided experiences; and

- other immediately accessible digital products.

Unless different refund terms are expressly provided at checkout, purchases of digital products that have been accessed, downloaded, substantially used, or completed may be non-refundable.

If you experience a technical problem that prevents you from accessing a product you purchased, please contact us so we can attempt to resolve the access issue.

A technical problem that Symmetricly can reasonably correct does not automatically require a refund.

## 3. Subscriptions

If you purchase a recurring subscription, you may cancel future renewal according to the cancellation options available for that subscription.

Cancellation stops future renewal charges after the cancellation becomes effective.

Unless otherwise stated for a particular subscription:

- cancellation does not automatically refund charges already processed;

- access may continue through the remainder of the paid billing period; and

- your subscription will not renew after the applicable paid period ends.

Canceling a subscription and requesting a refund are separate actions.

## 4. Refund Requests

If you believe a charge qualifies for a refund, contact Symmetricly at:

info@symmetricly.co

Include enough information for us to identify the transaction, such as:

- the email address associated with your account;

- the product purchased;

- the approximate purchase date; and

- the reason for your request.

Do not send full credit-card numbers or other unnecessary financial information by email.

Submitting a refund request does not guarantee that a refund will be approved.

We will evaluate requests according to this Policy, the terms applicable to the product, the circumstances of the transaction, and applicable law.

## 5. Full Refunds

When Symmetricly issues a full refund, access associated solely with the refunded purchase may be revoked when the refund is processed.

A full refund generally reverses the purchase that created the applicable paid entitlement.

Revocation of one refunded purchase will not necessarily remove access if you have another independent and valid source of access to the same product.

For example, another valid purchase, subscription, promotional entitlement, or authorized complimentary access may independently permit continued access.

A refund does not necessarily delete your Symmetricly account or information that may appropriately be retained under our Privacy Policy.

## 6. Partial Refunds

A partial refund does not automatically terminate access to the applicable product.

Partial refunds may be issued in circumstances such as:

- billing corrections;

- courtesy adjustments;

- partial service adjustments;

- pricing corrections; or

- other situations determined appropriate by Symmetricly.

Symmetricly may review access separately when circumstances surrounding a partial refund require additional action.

## 7. Duplicate or Erroneous Charges

If you believe you were charged more than once for the same intended purchase, contact us before initiating a payment dispute when reasonably possible.

We will review the transaction history and may refund a verified duplicate or erroneous charge.

Refunding one duplicate payment will not terminate access when another valid payment or entitlement continues to authorize access to the product.

## 8. Payment Disputes and Chargebacks

If you dispute a payment through your bank, card issuer, or payment provider, access associated with the disputed payment may be temporarily suspended while the dispute is pending.

A temporary dispute suspension is not necessarily a permanent termination of your account or stored content.

If the dispute is resolved in Symmetricly’s favor and the payment remains valid, access associated with that payment may be restored.

If the dispute is resolved against Symmetricly and the payment is reversed, access associated with that payment may be revoked.

If another independent and valid entitlement authorizes access to the same product, loss of one disputed entitlement may not eliminate your effective access.

Nothing in this section prevents you from exercising dispute or chargeback rights available to you under applicable law or through your financial institution.

## 9. Failed, Declined, or Reversed Payments

Access to paid products may require successful payment.

If a payment:

- fails;

- is declined;

- is canceled before completion;

- is reversed;

- is refunded in full; or

- otherwise becomes ineligible to support paid access,

Symmetricly may withhold, suspend, or revoke access associated with that payment.

Our systems may reconcile payment status with our payment processor to correct situations in which access was not properly granted or removed.

## 10. Promotional, Complimentary, and Administrative Access

Access provided without payment, including promotional, scholarship, complimentary, beta, testing, or administrative access, is not eligible for a monetary refund because no purchase price was paid for that access.

Such access may be subject to separate duration or eligibility conditions.

A refund or dispute associated with a separate Stripe/payment-based purchase does not automatically revoke an independent authorized complimentary or administrative entitlement.

## 11. Assessments

Because assessments may generate personalized educational results after responses are submitted, assessment purchases may have different refund restrictions from unused digital products.

Unless otherwise stated at checkout, an assessment that has been completed and for which results have been generated is generally not eligible for a refund solely because the user disagrees with, dislikes, or did not expect the results.

If a technical error prevents an assessment from functioning or prevents delivery of purchased results, contact us so we can investigate and attempt to correct the issue.

## 12. Courses, Programs, Workshops, and Events

Courses, educational programs, workshops, live events, professional programs, and similar offerings may have their own cancellation and refund deadlines.

When product-specific terms are provided during registration or checkout, those terms govern that purchase.

Those terms may address matters such as:

- cancellation deadlines;

- refunds before a program begins;

- refunds after accessing course materials;

- missed sessions or events;

- transfers or credits;

- cohort-based programs;

- continuing-education programs; and

- certification-related purchases.

Please review the applicable terms before purchasing.

## 13. Relationship Companion

Paid Relationship Companion access is governed by the purchase terms displayed for the applicable offering.

When a full refund is issued for the only valid purchase supporting Companion access, paid Companion access may be revoked.

A partial refund does not automatically revoke Companion access.

A payment dispute may temporarily suspend access associated with the disputed payment while the dispute is pending.

If a dispute is resolved in Symmetricly’s favor, qualifying access may be restored. If the payment is ultimately reversed, the applicable payment-based entitlement may be revoked.

Your stored Companion information is not automatically deleted merely because paid access is suspended, canceled, or revoked. Information is handled according to the Symmetricly Privacy Policy and applicable Companion privacy disclosures.

## 14. Cancellation Does Not Mean Data Deletion

Canceling a subscription, receiving a refund, or losing access to a paid product does not automatically constitute a request to delete your account or personal information.

Account and data-deletion requests are handled separately according to the Symmetricly Privacy Policy and applicable product controls.

Certain records may be retained for financial, security, fraud-prevention, audit, dispute-resolution, or other permitted purposes even after a product is refunded or access ends.

## 15. Refund Method and Processing

Approved refunds will generally be returned through the original payment method or payment-processing channel when available.

The time required for a refund to appear in your account may depend on the payment processor, bank, card issuer, or other financial institution.

Symmetricly does not control processing times imposed by independent financial institutions.

## 16. Abuse of Refunds or Promotions

Symmetricly may deny a discretionary refund request or restrict future purchases when there is reasonable evidence of fraud, repeated abuse of refund policies, unauthorized payment activity, manipulation of promotional offers, or other misuse.

This provision does not limit consumer rights provided by applicable law.

## 17. Changes to This Policy

We may update this Refund & Cancellation Policy as our products, payment systems, or business practices change.

The “Last Updated” date identifies the most recent revision.

The terms applicable to a completed purchase will be determined by the terms presented or applicable to that purchase and any rights provided by applicable law.

## 18. Contact Us

Questions or refund requests may be directed to:

**Symmetricly**  
Email: info@symmetricly.co  
Mailing address: 1246 Concord Rd, Smyrna, GA 30080

Please do not send full payment-card information by email.

This Refund & Cancellation Policy forms part of the Symmetricly Terms of Use where incorporated by reference.`,
  },
  "companion-privacy": {
    slug: "companion-privacy",
    title: "Relationship Companion\u2122 Privacy Disclosure",
    effectiveDate: "July 25, 2026",
    markdown: `This Relationship Companion™ Privacy Disclosure explains how information is handled when you use the Relationship Companion. It supplements the Symmetricly Privacy Policy and should be read together with that policy.

The Relationship Companion is a consumer relationship-wellness and educational tool based on the Relationship Life Cycle™ Framework. Because you may choose to write about personal relationships and sensitive life experiences, we want you to understand what information may be collected and how it may be used.

## 1. The Relationship Companion Is Separate From Clinical Services

The Relationship Companion is an educational relationship-wellness product. It is not psychotherapy, counseling, medical treatment, or another clinical service.

Information you enter into the Relationship Companion is used to provide the Companion’s educational and relationship-wellness features and is not intended to serve as a psychotherapy or clinical treatment record.

If you separately receive clinical services from a Symmetricly provider or affiliated clinical practice, those services are governed by the privacy notices, informed-consent documents, and other requirements applicable to your clinical care.

Your Relationship Companion entries are not intended to be automatically transferred into a clinical record, and a treating clinician should not be assumed to be monitoring your Companion activity.

Do not use the Relationship Companion to communicate urgent or clinical information to a therapist, healthcare professional, or other provider.

## 2. Information You May Choose to Provide

Depending on how you use the Relationship Companion, you may provide information such as:

- written reflections about your relationships;

- responses to guided exercises and prompts;

- information entered into your Blueprint, Planner, Journey, or other Companion features;

- relationship experiences, concerns, goals, and patterns;

- information about communication, trust, conflict, intimacy, roles, or other relationship experiences;

- information about your emotional experiences;

- information concerning violence, threats, sexual experiences, coercion, self-harm, or other safety concerns; and

- other information you voluntarily choose to enter.

You are not required to share information that you do not want to record digitally.

Because relationship experiences can be highly personal, consider the sensitivity of information before entering it into the Companion.

## 3. How Companion Information Is Used

Information you provide may be used to operate the Relationship Companion and deliver its educational features.

Depending on the feature, this may include using information to:

- save your entries and progress;

- provide guided relationship-learning experiences;

- organize your Blueprint, Planner, Journey, and other Companion content;

- determine which educational content or experience should appear next;

- personalize aspects of your Companion experience;

- maintain your account and access;

- operate automated safety-detection features;

- prevent fraud, abuse, or unauthorized access;

- maintain the security and reliability of the service; and

- support other purposes described in the Symmetricly Privacy Policy.

Information entered into the Companion should not be used for purposes materially different from those described to you without appropriate notice or authorization when required.

## 4. Automated Safety Detection

Free-text information entered into certain areas of the Relationship Companion may be processed by an automated Safety Detection Layer.

This system is designed to recognize some language that may indicate concerns involving:

- suicide or self-harm;

- intimate partner violence, threats, intimidation, or coercive control;

- sexual assault or sexual coercion;

- potential serious harm to another person; or

- possible immediate danger.

This processing is automated.

No person is continuously monitoring what you write in the Relationship Companion.

## 5. What Happens When a Safety Signal Is Detected

When certain safety-related language is detected, the Companion may:

- display a supportive notice;

- pause or modify the normal Companion experience;

- display crisis, domestic violence, sexual assault, emergency, or other support resources; or

- temporarily prioritize safety information over ordinary Relationship Life Cycle™ educational content.

The Companion does not automatically call emergency services, contact a hotline, contact another person, send an email or text on your behalf, or notify someone simply because safety-related language is detected.

The automated safety system is not a professional safety assessment.

## 6. Safety Event Information

The Relationship Companion is designed to minimize unnecessary duplication of sensitive disclosures when operating its safety features.

When the Safety Detection Layer identifies a safety signal, the system may create a structured safety-event record containing information such as:

- the category of safety signal detected;

- the response or action level;

- whether possible immediate danger was detected;

- classification information associated with the detection;

- the version of the safety system and rules that produced the classification;

- technical context necessary to operate or evaluate the safety feature; and

- timestamps and related operational metadata.

The safety-event system is designed not to create a separate copy of your raw written disclosure solely for safety-event logging.

Your original entry may still remain within the Companion feature where you chose to save it.

## 7. Limitations of Automated Safety Detection

Automated language detection is imperfect.

The system may:

- fail to recognize a safety concern;

- identify language as concerning when no safety concern exists;

- misunderstand context, humor, slang, figurative language, or indirect statements;

- misunderstand who or what a statement refers to; or

- incorrectly estimate the urgency of a situation.

Not receiving a safety message does not mean the Relationship Companion has determined that you are safe.

Likewise, receiving a safety message does not establish a diagnosis or definitive conclusion about you, another person, or your relationship.

Please review the Relationship Companion Informed Use & Safety Disclosure and Crisis & Safety Disclaimer for additional information.

## 8. Information About Other People

Your relationship experiences may involve partners, former partners, family members, or other people.

Please avoid entering unnecessary identifying information about another person.

When information such as another person’s full legal name, address, phone number, workplace, financial information, or other identifying information is unnecessary for your reflection, consider leaving it out.

The Relationship Companion is designed for your relationship education and reflection. It is not intended to serve as a repository for unnecessary personal information about other people.

## 9. Device and Browser Privacy

Someone with access to your phone, computer, browser, accounts, passwords, internet connection, or other technology may be able to see information about your activity.

If you are concerned that another person may monitor your device or internet activity, consider whether the device you are using is appropriate for entering sensitive information.

Certain safety-related screens may provide a Quick Exit feature.

Quick Exit is designed to help you leave a sensitive screen quickly. It does not erase browser history, device activity, network records, account activity, or other evidence that you used the Relationship Companion.

## 10. Third-Party Safety Resources

The Relationship Companion may display contact information or links for independent crisis, domestic violence, sexual assault, emergency, or other support organizations.

You decide whether to contact or visit these resources.

If you choose to contact or visit a third-party organization, information you provide to that organization is subject to its own privacy practices.

Symmetricly does not control the privacy practices of independent third-party support services.

## 11. Human Access to Companion Information

The Relationship Companion is not continuously monitored by Symmetricly staff.

Authorized personnel may have limited access to information when reasonably necessary to operate, secure, administer, maintain, troubleshoot, or support the Relationship Companion, subject to applicable access controls and company policies.

Technical accessibility for authorized operational purposes does not mean a person is reviewing your entries in real time.

## 12. Service Providers

Symmetricly may use technology providers and other service providers to operate portions of the Relationship Companion.

These services may include functions such as:

- website and application hosting;

- databases and data storage;

- authentication;

- payment processing;

- email and transactional communications delivery;

- security and fraud prevention;

- infrastructure and application operations; and

- other technology necessary to provide the service.

Information may be processed by service providers when reasonably necessary to perform services on Symmetricly’s behalf.

Additional information about service providers and data practices should be provided in the primary Symmetricly Privacy Policy where applicable.

## 13. Payments

Payment information and Relationship Companion content serve different purposes.

Third-party payment providers may process information necessary to manage purchases, subscriptions, refunds, disputes, and access to paid features.

The Relationship Companion’s Safety Detection Layer does not need your full payment-card information to evaluate safety-related language.

Payment providers maintain their own privacy and security practices.

## 14. Security

Symmetricly uses administrative, technical, and organizational safeguards intended to protect information associated with the Relationship Companion.

Access controls are designed to restrict access to authorized users and systems.

However, no website, application, database, electronic transmission, or digital storage system can be guaranteed to be completely secure.

Please consider this when deciding what information you are comfortable recording digitally.

## 15. Retention and Deletion

Relationship Companion information may be retained for as long as reasonably necessary to:

- provide the service;

- maintain account functionality;

- protect the security and integrity of the platform;

- maintain necessary financial or transaction records;

- prevent fraud or misuse;

- resolve disputes;

- enforce applicable agreements;

- comply with applicable requirements; or

- fulfill other purposes described in the Symmetricly Privacy Policy.

Deleting an account or particular Companion content may not necessarily remove information that must be retained for legitimate security, financial, fraud-prevention, audit, dispute-resolution, or other permitted purposes.

Any available deletion rights, retention periods, and procedures are governed by the primary Symmetricly Privacy Policy and applicable law.

## 16. Consumer Privacy Rights

Depending on where you live, you may have certain rights concerning your personal information.

These rights may include the ability to request access to, correction of, or deletion of certain personal information, or other rights provided under applicable privacy law.

The primary Symmetricly Privacy Policy explains available privacy rights, how to submit a request, and any limitations or exceptions that may apply.

## 17. Changes to This Disclosure

The Relationship Companion and its features may evolve over time.

If material changes are made to how Companion information is collected, used, or handled, this disclosure should be updated accordingly.

The effective date and last-updated date will identify the current version.

When appropriate, users may be asked to review or acknowledge materially revised disclosures before continuing to use the Companion.

## 18. Questions About Privacy

Questions about this Relationship Companion Privacy Disclosure or the privacy practices of the Companion may be submitted using the privacy contact information provided in the Symmetricly Privacy Policy.

For additional information, please review:

- the Symmetricly Privacy Policy;

- the Relationship Companion Informed Use & Safety Disclosure;

- the Relationship Companion Crisis & Safety Disclaimer; and

- the applicable Terms of Use.`,
  },
  "crisis": {
    slug: "crisis",
    title: "Relationship Companion\u2122 Crisis & Safety Disclaimer",
    effectiveDate: "July 25, 2026",
    markdown: `The Relationship Companion™ is an educational relationship-wellness tool. It is not therapy, crisis care, emergency services, or a substitute for professional support.

### This tool is not monitored in real time

No person is continuously monitoring what you write in the Relationship Companion.

Do not use the Companion to request emergency assistance or assume that someone from Symmetricly will see your response and contact you.

The Companion cannot dispatch emergency services or intervene in an emergency.

### About safety alerts

The Relationship Companion uses automated safety features designed to recognize some language that may indicate:

- thoughts of suicide or self-harm;

- violence, threats, fear, or coercive control involving a partner;

- sexual assault or sexual coercion;

- possible harm to another person; or

- possible immediate danger.

If certain language is detected, the Companion may pause your experience and show support or safety resources.

These alerts are not a professional safety assessment.

Automated detection can make mistakes. It may miss a safety concern or show a safety message when one is not needed.

Not receiving a safety alert does not mean the Companion has determined that you are safe.

### If you need help now

If you believe you or someone else may be in immediate danger, contact local emergency services when you can do so safely.

In the United States, call 911 for an immediate emergency.

The Companion may also provide crisis, domestic violence, sexual assault, or other support resources based on the concern detected and available resources for your location.

You choose whether to contact a resource. The Relationship Companion does not automatically call, text, email, or notify these services or anyone else because of something you write.

### If someone may be monitoring your device

Someone with access to your phone, computer, browser, accounts, or internet activity may be able to see your activity.

For certain safety concerns, the Companion may provide a Quick Exit option to help you leave the sensitive screen quickly.

Quick Exit does not erase your browsing history, device activity, network activity, or other evidence of your visit.

Consider using a device you believe is more private if you are concerned that someone is monitoring your activity.

### Remember

The Relationship Companion can provide education, reflection, and access to support information. It cannot determine whether you are safe, determine whether another person is dangerous, diagnose abuse, or make relationship or safety decisions for you.

When you are concerned about your safety or someone else’s safety, human support matters.`,
  },
};
