/*
 * Second pass: rewrite the REFLECTIVE blocks (intro / reflection x2 / emotion /
 * next-step / closing) of the 16 Recovery–Renewal draft experiences, grounded in
 * the RLC Framework Manual (Ch.6 Recovery / Ch.7 Renewal). Uses the manual's own
 * GROWTH-oriented reflection questions (Who am I now / what needs healing / what's
 * emerging / what will I carry forward / what am I building) — deliberately NOT the
 * rumination loops the manual names ("why wasn't I enough / what's wrong with me").
 * Prompts stay open and non-directive; the educational_note (block 3) is untouched.
 * Experiences remain status="draft" → owner review before publishing.
 *   (set -a; . ./.env.local; set +a; node scripts/authorRecoveryRenewalReflective.mjs)
 */
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "node:fs";
for (const line of readFileSync(process.cwd() + "/.env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/); if (m) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
}
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });

// situation_id → { intro, r1, emo, r2, next, closing } grounded in Recovery/Renewal chapters
const C = {
  "RS-0001": { intro: "In the Relationship Life Cycle, healing has its own timing — Recovery comes before turning back toward dating, and it can't be rushed. This is a space to be honest about where you are, without pressure to be further along.", r1: "Recovery asks, “What parts of myself still need healing?” What in you still feels tender or unfinished right now? Write freely.", emo: "What comes up as you sit with not being ready? Name whatever's there — there's no feeling you're supposed to have.", r2: "Healing was never meant to be a permanent residence — but you get to leave it when you're ready, not when others expect. What would tell you healing had progressed enough to even consider dating?", next: "What's one small step toward your own healing you could take this week — rest, support, a boundary? Note it.", closing: "Not being ready isn't falling behind; it's Recovery doing its work. You're allowed to stay here as long as you need. Come back whenever you want to check in with yourself." },
  "RS-0003": { intro: "Recovery isn't about forgetting — it's learning to carry an experience without letting it carry you. This is a space to look, gently, at what still holds your attention.", r1: "When your ex comes to mind, which question are you really asking — “Why did this happen?”, “What did I learn?”, “Who am I now?” Name what your mind keeps reaching for.", emo: "What emotions ride along with those thoughts? Name them without judging them.", r2: "Healing and pain can coexist. What might you still be carrying from this relationship — a lesson, a longing, a loss — that hasn't fully settled yet?", next: "What's one gentle thing you could do the next time the thoughts pull at you? Note it.", closing: "Still thinking about them isn't a failure or a setback — the memories and grief can remain even as you rebuild. Be patient with yourself. Come back whenever you need to." },
  "RS-0004": { intro: "In the Relationship Life Cycle, Recovery begins once reality has been accepted — and closure is part of that acceptance, something you build rather than receive. This is a space to work toward your own peace with how it ended.", r1: "Recovery often circles questions like “Why did this happen?” and “Could it have been different?” What are you still trying to understand or resolve about the ending? Write it out.", emo: "What are you feeling as you name that? Let it be whatever it is.", r2: "If the other person will never give you the answer you're waiting for, what would it take for you to accept reality enough to move forward anyway?", next: "Is there one thing — a letter you don't send, a ritual, a boundary — that would help you close this for yourself? Note it.", closing: "Closure is something you can give yourself; it doesn't require their cooperation. You're allowed to move at your own pace. Come back anytime." },
  "RS-0006": { intro: "Recovery is a phase of reconstruction, not just loss. As old routines and roles fall away, it opens the question “Who am I now?” This is a space to notice who you're becoming on your own.", r1: "Recovery asks, “What parts of myself are emerging?” When you're on your own lately, what feels new, or more like you? Write about a moment.", emo: "What comes up around being on your own right now? Name the feelings.", r2: "What matters to you now, and what kind of life do you want to create — as yourself, not as half of something? Describe it.", next: "What's one thing that steadies you or feels like yours that you could do more of? Note it.", closing: "Being alone isn't an empty gap between relationships — it's the rebuilding work of Recovery, where you become whole on your own terms. Come back whenever you want to." },
  "RS-0008": { intro: "The Relationship Life Cycle recognizes that Recovery often means grieving more than a person — including the future you imagined and the identity you held. This is a space to honor that loss, which is real even when no one else sees it.", r1: "What was the life you pictured? Describe it — the ordinary details, not just the milestones.", emo: "What are you feeling as you name that imagined life? Let it be here.", r2: "What parts of what you wanted were about that specific relationship — and what parts are things you can still want, and build another way?", next: "Is there one small way to honor what you've lost, or one hope you can carry forward? Note it.", closing: "Grieving a future that never got to happen is still grief, and it deserves care. Come back whenever you need to." },
  "RS-0009": { intro: "Recovery is a phase of reconstruction. A hard ending can shake the identity you held — and this framework treats that as the ground where a new sense of self begins to emerge. This is a space to start rebuilding.", r1: "What has this experience made you believe about yourself? Write the belief out plainly, even if it stings — naming it is how Recovery starts to loosen it.", emo: "What feelings come with that belief? Name them.", r2: "Recovery asks, “How have I grown? Who am I becoming?” Setting the ending aside, what's true about your worth that this experience didn't change?", next: "What's one thing you could do this week that reminds you who you are outside of a relationship? Note it.", closing: "Your worth didn't leave with them. Rebuilding your sense of self is the work of Recovery, and you're allowed to take your time. Come back anytime." },
  "RS-0002": { intro: "In the Relationship Life Cycle, Renewal is not a race and not a reset — it's an evolution that follows its own timing, not anyone else's schedule. This is a space to loosen the feeling of being “behind.”", r1: "Behind whom, and by whose measure? Whose timeline are you actually comparing yourself against? Write it out.", emo: "What feelings come up around that comparison? Name them plainly.", r2: "Renewal asks, “What do I want now? What am I building?” If no one's schedule but your own existed, what would you actually want more of?", next: "Is there one comparison you could set down this week — a feed to mute, a question to stop answering? Note it.", closing: "You're not running late — Renewal is an evolution at your own pace, carrying what you've learned. Come back anytime you want to loosen the grip of the timeline." },
  "RS-0005": { intro: "Renewal means moving forward carrying the wisdom of the past — not erasing it, and not simply returning to what was. This is a space to think clearly before history or feeling decides for you.", r1: "What's pulling you toward yes, and what's pulling you toward no? Write both honestly.", emo: "What are you feeling as you weigh this — hope, fear, relief, dread? Name it.", r2: "Renewal is a decision to engage possibility from who you are now. What was actually true when it ended — and what, specifically, would have to be different for returning to move you forward rather than back?", next: "What's one thing you'd want to see change or protect before deciding? Note it.", closing: "Whether this is renewal or repetition depends on whether it lets you carry your wisdom forward. You get to choose, on your own terms. Come back whenever you want to think it through again." },
  "RS-0007": { intro: "Recovery makes patterns visible, and Renewal lets that wisdom shape what you choose next. Noticing a recurring dynamic is exactly that wisdom surfacing. This is a space to look at it with curiosity, not blame.", r1: "Think of the people you've been drawn to. What do they share — in how they made you feel, not just who they were? What pattern became visible?", emo: "What comes up as you see the pattern? Name it.", r2: "Renewal asks you to carry the wisdom of the past forward. What might that familiar dynamic be trying to give you — and what would choosing from what you've learned look like instead?", next: "What's one early sign of the pattern you could learn to notice sooner? Note it.", closing: "Seeing the pattern is the wisdom that makes a different choice possible — that's Renewal, not repetition. Be gentle with yourself. Come back anytime." },
  "RS-0010": { intro: "In the Relationship Life Cycle, Renewal is not primarily about finding another relationship — it's about reengaging with life itself, and it isn't dependent on another person. This is a space to name and protect what's good about this season.", r1: "Renewal is reengaging with purpose, friendship, community, creativity, growth. Where in your life right now do you feel most engaged and alive? Write it out — be specific.", emo: "What does this season feel like at its best? Name it.", r2: "Renewal asks, “What am I building? What kind of life do I want to create now?” What do you want more of while you have this freedom?", next: "Is there one thing you want to do more of, for its own sake, this season? Note it.", closing: "A full, contented single season isn't a waiting room — it's Renewal itself, participating in life on your own terms. Come back whenever you want to." },
  "RS-0011": { intro: "The central question of Renewal is “How do I fully live again?” — and reengagement begins with a decision to engage possibility, not with a deadline. This is a space to tell the difference between ready and restless.", r1: "What's making you consider dating right now? Name the real reasons — loneliness, pressure, curiosity, genuine desire — as honestly as you can.", emo: "What are you feeling as you imagine putting yourself out there? Name it.", r2: "In this framework, dating is part of Renewal but not its definition — and healthy reengagement comes from healing, not from loss. Are you turning toward life, or away from being alone? What would “ready” actually look and feel like for you?", next: "Is there one thing you'd want in place first? Note it.", closing: "There's no deadline on readiness — reengagement is a choice you make from healing, not pressure. You're allowed to wait, or to try. Come back whenever you want to check in." },
  "RS-0012": { intro: "The Relationship Life Cycle is clear that Renewal requires courage — not the absence of fear, but the willingness to move forward despite it. This is a space to hold both the caution and the wanting.", r1: "What are you most afraid would happen if you opened up again? Write the fear out fully — naming it is how it stops running the show.", emo: "What feelings come with that fear? Name them.", r2: "Renewal doesn't wait for fear to disappear; it asks that fear no longer make every decision. What has the fear been protecting you from — and what has it been costing you?", next: "What's one small way you could stay open and honor your caution at the same time? Note it.", closing: "Wanting connection while fearing it is deeply human — and moving forward anyway is the courage Renewal asks for. You don't have to choose between safe and open all at once. Come back anytime." },
  "RS-0014": { intro: "Renewal is an evolution, not a reset — you move forward carrying the wisdom of the past. Wanting to do it differently is that wisdom becoming a plan. This is a space to make it concrete.", r1: "Looking back with what you now know, what do you most want to do differently — in who you choose, how you show up, or what you allow? Write it out.", emo: "What comes up as you imagine doing it differently? Name it.", r2: "The person entering Renewal isn't who they were before. What's one specific thing you'll do — or stop doing — that turns “differently” from an intention into a practice?", next: "What's the first small step toward that? Note it.", closing: "Different is built one choice at a time, from the wisdom you've earned. You already know more than you did before. Come back whenever you want to." },
  "RS-0016": { intro: "Renewal is the process of reengaging with life — community, friendship, shared interests, everyday connection — not just dating. This is a space to think about what participating in life again could look like for you.", r1: "Where in your ordinary week are you already around people — and where might you genuinely enjoy being more? Write out a few real places.", emo: "How do you feel about meeting people this way — excited, awkward, resistant? Name it.", r2: "Renewal is about turning toward life, not chasing a single outcome. What kinds of settings bring out a version of you that you like — and what would it take to be in one more often?", next: "What's one small, doable thing you could try this month? Note it.", closing: "Connection tends to find people who are showing up to life — which is the real work of Renewal. Start small and real. Come back whenever you want to." },
  "RS-0017": { intro: "Renewal means carrying the wisdom of the past forward — and that growth is one of your greatest resources. Worrying you'll miss the signs usually means you've already learned to take them seriously. This is a space to rebuild trust in your own judgment.", r1: "Looking back, what did you notice but talk yourself out of? Write what you actually saw — and what you told yourself instead.", emo: "What comes up as you name that? Name the feelings.", r2: "You don't reengage as the person you were before. What would help you trust and act on what you notice next time, instead of explaining it away?", next: "What's one thing you'll promise to take seriously if you see it again? Note it.", closing: "You likely saw more than you gave yourself credit for — and that wisdom is yours to carry into Renewal. Trusting yourself is a skill you can rebuild. Come back anytime." },
  "RS-0019": { intro: "In the Relationship Life Cycle, healthy Renewal is not dependent on another person — it begins with your own decision to engage possibility. This is a space to sort out whose choice this actually is.", r1: "Whose voices are telling you to date — and what are they actually saying? Write them out.", emo: "What do you feel when you imagine not dating right now? Name it.", r2: "Renewal is broader than dating, and it's yours to define. Setting everyone else aside, what would turning toward life look like for you right now — and does it even include dating yet?", next: "Is there one expectation you could set down, at least for now? Note it.", closing: "Reengagement is yours to choose or decline — pressure isn't the same as readiness. You don't owe anyone your love life. Come back whenever you want to." },
};

// block_order → field (educational_note at order 3 is left untouched)
const MAP = { 0: "intro", 1: "r1", 2: "emo", 4: "r2", 5: "next", 6: "closing" };

async function main() {
  const ids = Object.keys(C);
  const { data: exps } = await sb.from("companion_experiences").select("id,situation_id,status").eq("owner", "scaffold").in("situation_id", ids);
  let updated = 0;
  for (const e of exps ?? []) {
    if (e.status !== "draft") { console.log(`${e.situation_id}: not draft — skip`); continue; }
    const c = C[e.situation_id];
    let blockCount = 0;
    for (const [order, field] of Object.entries(MAP)) {
      const { error } = await sb.from("companion_experience_blocks")
        .update({ payload: { text: c[field] } })
        .eq("experience_id", e.id).eq("block_order", Number(order));
      if (error) { console.log(`${e.situation_id} block ${order}: ${error.message}`); continue; }
      blockCount++;
    }
    await sb.from("companion_experiences").update({
      internal_notes: "All blocks grounded in the RLC Framework Manual (Ch.6 Recovery / Ch.7 Renewal): reflective prompts use the manual's growth-oriented questions (not rumination loops); educational note from the same chapters. Still DRAFT — pending owner theory/safety review before publishing.",
    }).eq("id", e.id);
    console.log(`${e.situation_id}: ✅ ${blockCount} reflective blocks grounded in the manual`);
    updated++;
  }
  console.log(`\n✓ ${updated}/${ids.length} experiences updated. Reflective blocks manual-grounded; educational notes unchanged. All DRAFT.`);
}
main().catch((e) => { console.error("FAILED:", e.message); process.exit(1); });
